### ISSUE TITLE
DBW Node / Controller

### ISSUE THREAD

**Issue by xie-dongping** [sdc-team-southern-germany/CarND-Capstone#2]
Once your waypoint updater is publishing /final_waypoints, the waypoint_follower node will start publishing messages to the/twist_cmd topic. At this point, you have everything needed to build the dbw_node. After completing this step, the car should drive in the simulator, ignoring the traffic lights.

**Comment by klemense1** [comment]
Implemented basic longitudinal functionality for control. haven't tested it in ros yet.
cte still needs to be calculated in order to allow for control of steering.
